{"timestamp":"2025-07-20T18:51:03.169682","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-20T18:51:03.169997","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/complex_failure_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-20T18:51:03.195609Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-20T18:51:03.195758Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-20T18:51:03.195846Z","level":"info","event":"Current task name:sometimes_fail_task","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-20T18:51:03.195894Z","level":"info","event":"Dag name:complex_failure_dag","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-20T18:51:03.196747","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"IndexError","exc_value":"string index out of range","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":877,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1164,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/complex_failure_dag.py","lineno":34,"name":"sometimes_fail_task"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-20T18:51:03.221375Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-20T18:51:03.221552Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-20T18:51:03.221657Z","level":"info","event":"Task:<Task(PythonOperator): sometimes_fail_task>","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-20T18:51:03.221731Z","level":"info","event":"Failure caused by string index out of range","chan":"stdout","logger":"task"}
